name: Build Open1722

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y meson libcmocka0 libcmocka-dev lcov
    - name: Run build_all.sh script
      run: ./build_all.sh
    - name: Run test_all.sh
      run: ./test_all.sh
